### ISSUE TITLE
Modules to be open source?

### ISSUE THREAD

**Issue by LoganGar** [netherfoam/Titan#74]
Hello,

I am interested in the modules you've written for the server, any plans to release them as open source software?

Great looking project!
I am from Rune-Server.org, username is: "Logan"

**Comment by netherfoam** [comment]
There are a few issues with open sourcing the modules from my point of view:
* They're terribly written
* Versioning is difficult because minor changes in the framework cause modules to break

I'm also very protective of the AI players module because I've put a fair bit of thought into that one.

---

Are you instead, perhaps, looking for an example of a module or something?
